import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, BadgeDollarSign, Clock3, FileCheck2, Plus } from 'lucide-react';
import { io } from 'socket.io-client';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';
import QuoteStatusCard from '../components/QuoteStatusCard';

export default function Dashboard() { const { user } = useAuth(); const [quotes, setQuotes] = useState([]); const [notice, setNotice] = useState('');
  const load = () => api.get('/api/negotiation/quotes').then(({ data }) => setQuotes(data));
  useEffect(() => { load(); const socket = io(import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'); socket.emit(user.role === 'sales' ? 'join_sales_room' : 'join_buyer_room', user.id); const updateQuote = (quote) => { setQuotes((current) => [quote, ...current.filter((item) => item._id !== quote._id)]); setNotice('A quote just changed.'); setTimeout(() => setNotice(''), 3000); }; socket.on('quote_updated', updateQuote); socket.on('quote_history_updated', updateQuote); return () => socket.disconnect(); }, [user.id, user.role]);
  const accept = async (quote) => { const { data } = await api.post('/api/negotiation/accept', { quoteId: quote._id }); setQuotes((current) => current.map((item) => item._id === quote._id ? { ...item, ...data.quote, status: 'approved' } : item)); window.open(`${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'}${data.pdfUrl}`, '_blank', 'noopener,noreferrer'); };
  const approved = quotes.filter((q) => q.status === 'approved').length; const pending = quotes.filter((q) => q.status === 'pending' || q.status === 'countered').length;
  return <><div className="page-wrap">{notice && <div className="fixed right-5 top-5 z-50 bg-ink px-4 py-3 text-sm font-bold text-white shadow-lg">{notice}</div>}<div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Buyer overview</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Good morning, {user.name.split(' ')[0]}.</h1><p className="mt-2 text-slate-500">Your commercial activity, in one clear view.</p></div><Link to="/products" className="inline-flex items-center justify-center gap-2 bg-coral px-5 py-3 text-sm font-bold text-white"><Plus size={17} />Start a negotiation</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="metric"><BadgeDollarSign className="text-coral" size={22} /><p className="mt-5 text-3xl font-bold text-ink">{quotes.length}</p><p className="text-sm text-slate-500">Total quotes</p></div><div className="metric"><Clock3 className="text-orange-600" size={22} /><p className="mt-5 text-3xl font-bold text-ink">{pending}</p><p className="text-sm text-slate-500">Need attention</p></div><div className="metric"><FileCheck2 className="text-emerald-700" size={22} /><p className="mt-5 text-3xl font-bold text-ink">{approved}</p><p className="text-sm text-slate-500">Approved orders</p></div></div><div className="mt-12 flex items-center justify-between"><div><p className="eyebrow">Recent activity</p><h2 className="mt-2 font-display text-2xl font-bold text-ink">Your quote pipeline</h2></div><Link to="/products" className="inline-flex items-center gap-1 text-sm font-bold text-ink">Browse catalog <ArrowUpRight size={16} /></Link></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{quotes.length ? quotes.map((quote) => <QuoteStatusCard key={quote._id} quote={quote} onAccept={accept} />) : <div className="border border-dashed border-slate-300 p-10 text-center text-slate-500 lg:col-span-2">No quotes yet. Browse the catalog to make your first offer.</div>}</div></div></>;
}