import PDFDocument from 'pdfkit';

export const createPurchaseOrderPdf = ({ quote, buyer, product }) => {
  const document = new PDFDocument({ margin: 56 });
  const chunks = [];
  document.on('data', (chunk) => chunks.push(chunk));
  const complete = new Promise((resolve) => document.on('end', () => resolve(Buffer.concat(chunks))));
  const unitPrice = quote.counterUnitPrice || quote.offeredUnitPrice;
  document.fontSize(22).fillColor('#17202a').text('PURCHASE ORDER', { align: 'right' });
  document.moveDown(2).fontSize(11).fillColor('#475569').text(`Quote ID: ${quote._id}`)
    .text(`Generated: ${new Date().toLocaleString()}`);
  document.moveDown().fontSize(14).fillColor('#17202a').text('Buyer details');
  document.fontSize(11).fillColor('#475569').text(`${buyer.name} | ${buyer.email}`);
  document.moveDown().fontSize(14).fillColor('#17202a').text('Order details');
  document.fontSize(11).fillColor('#475569').text(`Product: ${product.name} (${product.sku})`)
    .text(`Description: ${product.description}`)
    .text(`Quantity: ${quote.requestedQty}`)
    .text(`Payment terms: ${quote.customPaymentTerms || quote.paymentTerms || 'NET_30'}`)
    .text(`Term adjustment: ${quote.paymentTermAdjustmentPercentage || 0}%`)
    .text(`Approved unit price: $${unitPrice.toFixed(2)}`)
    .text(`Total amount: $${(unitPrice * quote.requestedQty).toFixed(2)}`);
  document.moveDown(2).fontSize(10).fillColor('#64748b').text('This purchase order was generated by the B2B Dynamic Price Negotiation Engine.');
  document.end();
  return complete;
};