import { useEffect, useState } from 'react';
import { Check, LoaderCircle, RefreshCw, ShieldOff } from 'lucide-react';
import api from '../api/axios';
import SupplierBadge from './SupplierBadge';

export default function AdminSupplierManager() {
  const [suppliers, setSuppliers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); api.get('/api/suppliers').then(({ data }) => setSuppliers(data)).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load suppliers')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const verify = async (supplier, tier) => { await api.patch(`/api/suppliers/${supplier._id}/verification`, { tier }); load(); };
  if (loading) return <div className="page-wrap flex min-h-[50vh] items-center justify-center"><LoaderCircle className="animate-spin text-coral" /></div>;
  return <div className="page-wrap"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Admin console</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Supplier verification.</h1><p className="mt-2 text-slate-500">Review documents, GSTIN status, and marketplace trust.</p></div><button onClick={load} className="inline-flex items-center gap-2 border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><RefreshCw size={16} />Refresh</button></div>{error && <p className="mt-6 border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-10 space-y-4">{suppliers.length ? suppliers.map((supplier) => <article key={supplier._id} className="border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-display text-2xl font-bold text-ink">{supplier.name}</h2><SupplierBadge supplier={supplier} /></div><p className="mt-2 text-sm text-slate-500">{supplier.legalName || supplier.email} · GSTIN: {supplier.gstin || 'Not submitted'}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => verify(supplier, 'Gold')} className="inline-flex items-center gap-2 bg-ink px-3 py-2 text-xs font-bold text-white"><Check size={14} />Gold</button><button onClick={() => verify(supplier, 'Silver')} className="border border-slate-200 px-3 py-2 text-xs font-bold text-ink">Silver</button><button onClick={() => verify(supplier, 'Unverified')} className="inline-flex items-center gap-2 border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><ShieldOff size={14} />Revoke</button></div></div><div className="mt-6 grid gap-4 text-sm sm:grid-cols-4"><div><p className="text-slate-400">Compliance score</p><p className="mt-1 font-bold text-ink">{supplier.complianceScore}/100</p></div><div><p className="text-slate-400">GSTIN status</p><p className="mt-1 font-bold capitalize text-ink">{supplier.gstinStatus}</p></div><div><p className="text-slate-400">Verified documents</p><p className="mt-1 font-bold text-ink">{(supplier.documents || []).filter((document) => document.status === 'verified').length}</p></div><div><p className="text-slate-400">Trade history</p><p className="mt-1 font-bold text-ink">{supplier.tradeHistory?.completedOrders || 0} orders</p></div></div></article>) : <div className="border border-dashed border-slate-300 p-10 text-center text-slate-500">No supplier applications yet.</div>}</div></div>;
}