import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, Check, Clock3, LoaderCircle, X } from 'lucide-react';
import api from '../api/axios';

const roleLabels = { buyer: 'You', system: 'Pricing engine', sales: 'Sales', admin: 'Admin' };
const paymentOptions = [['NET_15', 'Net 15'], ['NET_30', 'Net 30'], ['NET_60', 'Net 60'], ['NET_90', 'Net 90'], ['MILESTONE', 'Custom milestones']];
const defaultAdjustments = { NET_15: -2, NET_30: 0, NET_60: 1.5, NET_90: 1.5, MILESTONE: 0 };

function HistoryTimeline({ history = [] }) {
  return <div className="mt-8"><div className="flex items-center justify-between"><p className="eyebrow">Negotiation timeline</p><span className="text-xs font-bold text-slate-400">{history.length} turns</span></div><div className="mt-4 space-y-4 border-l border-slate-200 pl-5">{history.map((turn, index) => <div key={`${turn.timestamp}-${index}`} className="relative"><span className={`absolute -left-[25px] top-1.5 h-2.5 w-2.5 rounded-full ${turn.senderRole === 'buyer' ? 'bg-coral' : 'bg-ink'}`} /><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-ink">{roleLabels[turn.senderRole] || turn.senderRole}</p><p className="mt-1 text-xs text-slate-500">{turn.note || 'Offer submitted'} · {new Date(turn.timestamp).toLocaleString()}</p></div><p className="font-display text-lg font-bold text-ink">${Number(turn.unitPrice).toFixed(2)}</p></div><p className="mt-1 text-xs text-slate-400">{turn.quantity} units</p></div>)}</div></div>;
}

export default function NegotiationSlideOver({ product, onClose, onSubmitted }) {
  const [quantity, setQuantity] = useState(10); const [price, setPrice] = useState(''); const [paymentTerms, setPaymentTerms] = useState('NET_30'); const [customPaymentTerms, setCustomPaymentTerms] = useState(''); const [rule, setRule] = useState(null); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.get(`/api/pricing-rules/product/${product._id}`).then(({ data }) => setRule(data)).catch(() => setRule(null)); }, [product._id]);
  const availableStock = product.availableStock ?? Math.max(0, (product.currentStock || 0) - (product.reservedStock || 0));
  const stockStatus = availableStock === 0 ? 'Backorder required' : availableStock <= (product.reorderPoint || 0) ? 'Low stock' : 'In stock';
  const tier = useMemo(() => rule?.tierDiscounts?.slice().sort((a, b) => b.minQty - a.minQty).find((item) => Number(quantity) >= item.minQty), [quantity, rule]);
  const standard = rule ? rule.baseUnitPrice * (1 - (tier?.discountPercentage || 0) / 100) : 0;
  const configuredFloor = product.costPrice != null && product.minMarginPercentage != null ? product.costPrice / (1 - product.minMarginPercentage / 100) : 0;
  const minimumAllowedPrice = Math.max(rule?.minimumMarginFloorPrice || 0, configuredFloor);
  const termRule = rule?.paymentTermAdjustments?.find((item) => item.term === paymentTerms);
  const adjustmentPercentage = termRule?.adjustmentPercentage ?? defaultAdjustments[paymentTerms];
  const payablePrice = Number((Number(price || 0) * (1 + adjustmentPercentage / 100)).toFixed(2));
  const payableTotal = payablePrice * Number(quantity || 0);
  const termBlocked = termRule?.allowed === false || (paymentTerms === 'MILESTONE' ? rule?.allowMilestonePayments === false : ['NET_60', 'NET_90'].includes(paymentTerms) && Number(rule?.maxPaymentTermDays ?? 90) < Number(paymentTerms.slice(4)));
  const stockWarning = Number(quantity || 0) > availableStock;
  const guardrailWarning = price !== '' && (payablePrice < minimumAllowedPrice * (1 + adjustmentPercentage / 100) || termBlocked);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const endpoint = result ? '/api/negotiation/counter' : '/api/negotiation/submit'; const payload = result ? { quoteId: result.quote._id, offeredUnitPrice: Number(price), paymentTerms, customPaymentTerms } : { productId: product._id, requestedQty: Number(quantity), offeredUnitPrice: Number(price), paymentTerms, customPaymentTerms }; const { data } = await api.post(endpoint, payload); setResult(data); onSubmitted(data.quote); } catch (err) { setError(err.response?.data?.message || 'Unable to submit quote'); } finally { setBusy(false); } };
  const quoteStatus = result?.quote?.status;
  return <div className="fixed inset-0 z-40 flex justify-end bg-ink/30"><div className="h-full w-full max-w-xl overflow-y-auto bg-paper p-6 shadow-2xl sm:p-9"><div className="flex items-start justify-between"><div><p className="eyebrow">Negotiate item</p><h2 className="mt-2 font-display text-3xl font-bold text-ink">{product.name}</h2><p className="mt-2 text-sm text-slate-500">{product.sku} · {product.category}</p></div><button onClick={onClose} className="icon-button"><X size={20} /></button></div>
    <div className={`mt-6 border p-4 ${stockWarning ? 'border-orange-200 bg-orange-50 text-orange-900' : 'border-emerald-200 bg-mint text-emerald-900'}`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em]">Live inventory</p><p className="mt-1 font-bold">{availableStock} units available now</p></div><span className="text-xs font-bold uppercase">{stockStatus}</span></div><p className="mt-2 text-xs">{stockWarning ? `${Math.max(0, Number(quantity || 0) - availableStock)} units will be fulfilled after restock${product.leadTimeDays ? ` in approximately ${product.leadTimeDays} days` : ''}.` : 'Your requested quantity can be fulfilled from current inventory.'}</p></div>
    {result && <div className={`mt-8 flex items-center gap-3 border p-4 text-sm font-bold ${quoteStatus === 'approved' ? 'border-emerald-200 bg-mint text-emerald-800' : quoteStatus === 'rejected' ? 'border-red-200 bg-red-50 text-red-800' : 'border-orange-200 bg-orange-50 text-orange-800'}`}><span>{quoteStatus === 'approved' ? <Check size={18} /> : quoteStatus === 'rejected' ? <AlertTriangle size={18} /> : <Clock3 size={18} />}</span>{quoteStatus === 'approved' ? 'Approved at this price' : quoteStatus === 'rejected' ? 'Offer rejected by guardrail' : 'Counter offer returned'}{result.negotiation?.stockFulfillmentStatus !== 'in_stock' && <span className="ml-auto text-xs font-normal">Partial/backorder terms included</span>}</div>}
    {result && <HistoryTimeline history={result.quote.history} />}
    {(!result || quoteStatus === 'countered' || quoteStatus === 'rejected') && <form onSubmit={submit} className="mt-8 space-y-6"><div><label className="label">Quantity</label><input className="input" type="number" min="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /></div><div><label className="label">Payment terms</label><select className="input" value={paymentTerms} onChange={(event) => setPaymentTerms(event.target.value)}>{paymentOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{paymentTerms === 'MILESTONE' && <input className="input mt-3" value={customPaymentTerms} onChange={(event) => setCustomPaymentTerms(event.target.value)} placeholder="Describe milestones and due dates" required />}</div><div><label className="label">{result ? 'Your next unit price' : 'Target unit price'}</label><div className="relative"><span className="absolute left-4 top-3.5 text-slate-400">$</span><input className="input pl-8" type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} placeholder={standard ? standard.toFixed(2) : '0.00'} required /></div></div>{rule && <div className="border border-slate-200 bg-white p-4"><div className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-slate-400">Standard unit price</p><p className="mt-1 font-display text-xl font-bold text-ink">${standard.toFixed(2)}</p></div><div><p className="text-slate-400">Payable unit price</p><p className="mt-1 font-display text-xl font-bold text-ink">${payablePrice.toFixed(2)}</p></div></div><p className="mt-3 text-xs text-slate-500">{adjustmentPercentage < 0 ? `${Math.abs(adjustmentPercentage)}% early-payment discount` : adjustmentPercentage > 0 ? `${adjustmentPercentage}% financing surcharge` : 'Standard payment pricing'} · Estimated total <strong>${payableTotal.toFixed(2)}</strong></p><div className="mt-3 flex flex-wrap gap-2">{rule.tierDiscounts.slice().sort((a, b) => a.minQty - b.minQty).map((item) => <span key={item.minQty} className="bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{item.minQty}+ units · {item.discountPercentage}% off</span>)}</div></div>}{guardrailWarning && <div className="flex gap-3 border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle size={18} className="shrink-0" /><p>{termBlocked ? 'These payment terms exceed the supplier cash-flow policy.' : `This combination breaches the realized margin floor of $${minimumAllowedPrice.toFixed(2)} per unit.`}</p></div>}{error && <p className="text-sm font-medium text-red-700">{error}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 bg-ink px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? <LoaderCircle className="animate-spin" size={16} /> : <ArrowRight size={16} />}{result ? 'Submit counter offer' : 'Submit offer'}</button></form>}
    {result && quoteStatus === 'approved' && <button onClick={onClose} className="mt-8 flex w-full items-center justify-center gap-2 bg-ink px-5 py-3 text-sm font-bold text-white">View quote in dashboard <ArrowRight size={16} /></button>}
  </div></div>;
}